import React from 'react'
import { Button, Select } from '../index';
import {NotebookText, SquarePen, Trash2} from 'lucide-react'
import {piStatusOptions} from '../../assets/utils'
import { useNavigate } from 'react-router-dom';

const PICard = ({invoice, onDelete,onStatusChange, userData }) => {
  const navigate = useNavigate();
  const userRole = userData?.role;
  const isAuthor = invoice?.generated_by_id === userData?.uid;
  
  const showEditButton = isAuthor || userRole === 'superuser';
  const showGeneratedBy = userRole === 'admin' || userRole === 'superuser';
  
  return (
    <>
    <div className={`bg-white p-4 md:py-6 flex hover:bg-slate-50 flex-col cursor-pointer justify-start border border-gray-200 lg:border-0 lg:border-b-1 lg:grid ${showGeneratedBy? 'lg:grid-cols-9' : 'lg:grid-cols-8'} lg:gap-3 lg:items-center lg:text-center`} key={invoice.id}>
      <div className="mb-4 lg:mb-0 text-md pb-2 lg:pb-0 lg:col-span-1 flex text-start" onClick={() => navigate(`/performa-invoices/${invoice.id}`)} >
        <p className="font-semibold text-blue-700">{invoice.pi_number}</p>
      </div>
      <div className="lg:col-span-2 mb-2 lg:mb-0 flex lg:flex-col text-sm gap-1 lg:gap-0  flex-wrap" onClick={() => navigate(`/performa-invoices/${invoice.id}`)} >
        <p className="font-normal lg:hidden lg:text-xs text-gray-500">Client:</p>
        <p className="font-normal">{invoice.billing.firm}</p>
        {/* <p className="text-gray-500">{invoice.contact_number}</p> */}
      </div>
      
      <div className="mb-2 lg:mb-0 flex lg:flex-col text-sm gap-1 lg:gap-0  flex-wrap" onClick={() => navigate(`/performa-invoices/${invoice.id}`)} >
        <p className="font-normal lg:hidden lg:text-xs text-gray-500">Amount:</p>
        <p className="text-sm">₹{invoice.totals.grandTotal.toFixed(2)}</p>
      </div>

      <div className="mb-2 lg:mb-0 flex lg:flex-col text-sm gap-1 lg:gap-0 flex-wrap" onClick={() => navigate(`/performa-invoices/${invoice.id}`)} >
        <p className="font-normal lg:hidden lg:text-xs text-gray-500">Invoice Date:</p>
        <p className="text-sm">{invoice.pi_date}</p>
      </div>
       {showGeneratedBy && (
      <div className="mb-4 lg:mb-0 text-sm flex lg:flex-col gap-1 lg:gap-0 flex-wrap" onClick={() => navigate(`/performa-invoices/${invoice.id}`)} >
        <p className="font-normal lg:hidden lg:text-xs text-gray-500">Generated By:</p>
        <p>{invoice.generated_by_name}</p>
      </div>) 
      }
      <div className="mb-2 lg:mb-0 flex lg:flex-col text-sm gap-1 lg:gap-0 flex-wrap lg:justify-center" onClick={() => navigate(`/performa-invoices/${invoice.id}`)} >
          <div
            className={`py-1/2 px-2 flex lg:flex items-center gap-1 text-[10px] leading-5 font-bold rounded-full outline ${
              invoice.status === 'paid' ? 'bg-emerald-100 text-emerald-800' : invoice.status === 'unpaid' ?  'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800'
            }`}>
            <div className='h-2 w-2 rounded-full bg-white outline'></div>{invoice.status.toUpperCase()}
          </div>
      </div>

      <div className="lg:col-span-2 flex flex-row lg:justify-around justify-between lg:pt-0 lg:items-center cursor-default gap-2 lg:mt-0 pt-4">
        <Select
            placeholder="Select status"
            defaultValue={invoice.status}
            onChange={(e) => onStatusChange(invoice.id, e.target.value)}
            className="text-sm !w-fit !py-1"
            options={piStatusOptions}
          />
        {showEditButton &&
            <>
              <Button
                variant='ghost'
                size='small'
                onClick={() => navigate(`/performa-invoices/${invoice.id}`)}>
                <NotebookText className='w-4 h-4 text-blue-500' />
              </Button>
              <Button
                variant='ghost'
                size='small'
                onClick={() => navigate(`/performa-invoices/${invoice.id}/edit`)}>
                <SquarePen className='w-4 h-4'/>
              </Button>
              <Button
                textColor='text-red-700'
                variant='ghost'
                size='small'
                onClick={() => onDelete(invoice.id, invoice.pi_number)}>
                <Trash2 className='w-4 h-4 text-red-500'/>
              </Button>
            </>
          }
      </div>
    </div>
    </>
  )
}

export default PICard